import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/src/providers";
import { Toaster } from "@/src/components/ui/toaster";
import Layout from "@/src/components/layout/layout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Ajunet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable}`}>
        <Providers>
          {/* <AuthLayout> */}
          <Layout>{children}</Layout>
          {/* </AuthLayout> */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
